name: jstock
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  dropdown_search: ^6.0.2
  flutter:
    sdk: flutter
  flutter_spinbox: ^0.13.1
  get: ^4.6.6
  http: ^1.3.0
  intl: ^0.20.2
  pdf: ^3.11.2
  printing: ^5.14.0
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  flutter_test:
    sdk: flutter
